[package]
name = "wifi-cli"
version = "0.1.0"
authors = ["Tochukwu Nkemdilim <nkemdilimtochukwu@gmail.com>"]

[dependencies]
clap = { version = "2.31.2", features = ["yaml"] }
wifi-rs = { path = "../../../wifi-rs" }